defaults:
  - _self_

mode:
  train: True
  sample: True
  dataset: "mnist" # "mnist" or "cifar10"
  sample_size: 10

model:
  in_channels: 1
  out_channels: 1
  time_dim: 1000
  seed: 1

training:
  train_size: 1000
  test_size: 100
  optimizer: Adam # Adam, SGD
  weight_decay: 0.001 # 1e-2
  learning_rate: 0.01
  lr_scheduler: None # None, StepLR, ExponentialLR, ReduceLROnPlateau, CosineAnnealingLR
  batch_size: 100
  epochs: 100
  beta_scheduler: "Cosine" # Linear, Cosine
  beta_lower: 0.0001 
  beta_upper: 0.02
  early_stopping: True
  neptune: False
