defaults:
  - _self_

mode:
  train: False
  sample: True
  dataset: "cifar10" # "mnist" or "cifar10"
  sample_size: 10

model:
  in_channels: 3
  out_channels: 3
  time_dim: 1000
  seed: 1

training:
  train_size: 12800
  test_size: 1280
  optimizer: Adam # Adam, SGD
  weight_decay: 0.001 # 1e-2
  learning_rate: 0.01
  lr_scheduler: StepLR # None, StepLR, ExponentialLR, ReduceLROnPlateau, CosineAnnealingLR
  batch_size: 128
  epochs: 100
  beta_lower: 0.0001 
  beta_upper: 0.02
  early_stopping: False
  neptune: False
