defaults:
  - _self_

mode:
  train: True
  sample: True
  dataset: "cifar10" # "mnist" or "cifar10"

model:
  in_channels: 3
  out_channels: 3
  time_dim: 1000
  seed: 1

training:
  train_size: 10000
  test_size: 500
  optimizer: Adam # Adam, SGD
  weight_decay: 1e-2
  learning_rate: 0.01
  lr_scheduler: StepLR # StepLR, ExponentialLR, ReduceLROnPlateau, CosineAnnealingLR
  batch_size: 100
  epochs: 30
  beta_lower: 0.0001 
  beta_upper: 0.02
  early_stopping: True
