defaults:
  - _self_

mode:
  train: True
  sample: True
  dataset: "mnist" # "mnist" or "cifar10"

model:
  in_channels: 1
  out_channels: 1
  time_dim: 1000
  seed: 1

training:
  train_size: 10000
  test_size: 100
  learning_rate: 0.0001
  batch_size: 50
  epochs: 1000
  beta_lower: 0.0001 
  beta_upper: 0.02
  early_stopping: true
  weight_decay: 1e-2
