defaults:
  - _self_

mode:
  train: True
  sample: True
  dataset: "mnist" # "mnist" or "cifar10"

model:
  in_channels: 1
  out_channels: 1
  time_dim: 1000
  seed: 42

training:
  learning_rate: 0.0001
  batch_size: 1
  epochs: 5000
  beta_lower: 0.0001 
  beta_upper: 0.02
